### ISSUE TITLE
A question about the codes

### ISSUE THREAD

**Issue by THSWind** [Kchu/DeepRL_PyTorch#1]
3_IQN.py:264: UserWarning: Using a target size (torch.Size([32, 1, 64])) that is different to the input size (torch.Size([32, 64, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

**Comment by Kchu** [comment]
This is not a bug. I suggest you look at the specific calculation formula of Quantile Huber Loss. If you have any other questions, please feel free to contact me by email.
