### ISSUE TITLE
About handling the marginal cases in C51

### ISSUE THREAD

**Issue by Bowen-He** [Kchu/DeepRL_PyTorch#2]
Hi, I'm just wondering how you were handling the marginal case in C51, where lower bound == upper bound == next_v_position. From what I've read, it seems be disappearing in the code.... Remind me if I make a mistake here.

**Comment by Kchu** [comment]
Sorry, I just saw the issue you submitted, you can email me directly next time. I don't think you need to give special consideration to this situation. Moreover, I strongly recommend you to read the paper of C51 carefully. I believe with the help of this blog (https://reinforcement-learning-kr.github.io/2018/10/02/C51/), you will get a deeper understanding. Good luck!
